#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include "badge.h"

extern struct framebuf out0101_png;
extern struct framebuf out0102_png;
extern struct framebuf out0103_png;
extern struct framebuf out0104_png;
extern struct framebuf out0105_png;
extern struct framebuf out0106_png;
extern struct framebuf out0107_png;
extern struct framebuf out0108_png;
extern struct framebuf out0109_png;
extern struct framebuf out0110_png;
extern struct framebuf out0111_png;
extern struct framebuf out0112_png;
extern struct framebuf out0113_png;
extern struct framebuf out0114_png;
extern struct framebuf out0115_png;
extern struct framebuf out0116_png;
extern struct framebuf out0117_png;
extern struct framebuf out0118_png;
extern struct framebuf out0119_png;
extern struct framebuf out0120_png;
extern struct framebuf out0121_png;
extern struct framebuf out0122_png;
extern struct framebuf out0123_png;
extern struct framebuf out0124_png;
extern struct framebuf out0125_png;
extern struct framebuf out0126_png;
extern struct framebuf out0127_png;
extern struct framebuf out0128_png;
extern struct framebuf out0129_png;
extern struct framebuf out0130_png;
extern struct framebuf out0131_png;
extern struct framebuf out0132_png;
extern struct framebuf out0133_png;
extern struct framebuf out0134_png;
extern struct framebuf out0135_png;
extern struct framebuf out0136_png;
extern struct framebuf out0137_png;
extern struct framebuf out0138_png;
extern struct framebuf out0139_png;
extern struct framebuf out0140_png;
extern struct framebuf out0141_png;
extern struct framebuf out0142_png;
extern struct framebuf out0143_png;
extern struct framebuf out0144_png;
extern struct framebuf out0145_png;
extern struct framebuf out0146_png;
extern struct framebuf out0147_png;
extern struct framebuf out0148_png;
extern struct framebuf out0149_png;
extern struct framebuf out0150_png;
extern struct framebuf out0151_png;
extern struct framebuf out0152_png;
extern struct framebuf out0153_png;
extern struct framebuf out0154_png;
extern struct framebuf out0155_png;
extern struct framebuf out0156_png;
extern struct framebuf out0157_png;
extern struct framebuf out0158_png;
extern struct framebuf out0159_png;
extern struct framebuf out0160_png;
extern struct framebuf out0161_png;
extern struct framebuf out0162_png;
extern struct framebuf out0163_png;
extern struct framebuf out0164_png;
extern struct framebuf out0165_png;
extern struct framebuf out0166_png;
extern struct framebuf out0167_png;
extern struct framebuf out0168_png;
extern struct framebuf out0169_png;
extern struct framebuf out0170_png;
extern struct framebuf out0171_png;
extern struct framebuf out0172_png;

int timeout = 100000;

void main(void){
	while (1){
	framebuf_render(&out0101_png);
	usleep(timeout);
	framebuf_render(&out0102_png);
	usleep(timeout);
	framebuf_render(&out0103_png);
	usleep(timeout);
	framebuf_render(&out0104_png);
	usleep(timeout);
	framebuf_render(&out0105_png);
	usleep(timeout);
	framebuf_render(&out0106_png);
	usleep(timeout);
	framebuf_render(&out0107_png);
	usleep(timeout);
	framebuf_render(&out0108_png);
	usleep(timeout);
	framebuf_render(&out0109_png);
	usleep(timeout);
	framebuf_render(&out0110_png);
	usleep(timeout);
	framebuf_render(&out0111_png);
	usleep(timeout);
	framebuf_render(&out0112_png);
	usleep(timeout);
	framebuf_render(&out0113_png);
	usleep(timeout);
	framebuf_render(&out0114_png);
	usleep(timeout);
	framebuf_render(&out0115_png);
	usleep(timeout);
	framebuf_render(&out0116_png);
	usleep(timeout);
	framebuf_render(&out0117_png);
	usleep(timeout);
	framebuf_render(&out0118_png);
	usleep(timeout);
	framebuf_render(&out0119_png);
	usleep(timeout);
	framebuf_render(&out0120_png);
	usleep(timeout);
	framebuf_render(&out0121_png);
	usleep(timeout);
	framebuf_render(&out0122_png);
	usleep(timeout);
	framebuf_render(&out0123_png);
	usleep(timeout);
	framebuf_render(&out0124_png);
	usleep(timeout);
	framebuf_render(&out0125_png);
	usleep(timeout);
	framebuf_render(&out0126_png);
	usleep(timeout);
	framebuf_render(&out0127_png);
	usleep(timeout);
	framebuf_render(&out0128_png);
	usleep(timeout);
	framebuf_render(&out0129_png);
	usleep(timeout);
	framebuf_render(&out0130_png);
	usleep(timeout);
	framebuf_render(&out0131_png);
	usleep(timeout);
	framebuf_render(&out0132_png);
	usleep(timeout);
	framebuf_render(&out0133_png);
	usleep(timeout);
	framebuf_render(&out0134_png);
	usleep(timeout);
	framebuf_render(&out0135_png);
	usleep(timeout);
	framebuf_render(&out0136_png);
	usleep(timeout);
	framebuf_render(&out0137_png);
	usleep(timeout);
	framebuf_render(&out0138_png);
	usleep(timeout);
	framebuf_render(&out0139_png);
	usleep(timeout);
	framebuf_render(&out0140_png);
	usleep(timeout);
	framebuf_render(&out0141_png);
	usleep(timeout);
	framebuf_render(&out0142_png);
	usleep(timeout);
	framebuf_render(&out0143_png);
	usleep(timeout);
	framebuf_render(&out0144_png);
	usleep(timeout);
	framebuf_render(&out0145_png);
	usleep(timeout);
	framebuf_render(&out0146_png);
	usleep(timeout);
	framebuf_render(&out0147_png);
	usleep(timeout);
	framebuf_render(&out0148_png);
	usleep(timeout);
	framebuf_render(&out0149_png);
	usleep(timeout);
	framebuf_render(&out0150_png);
	usleep(timeout);
	framebuf_render(&out0151_png);
	usleep(timeout);
	framebuf_render(&out0152_png);
	usleep(timeout);
	framebuf_render(&out0153_png);
	usleep(timeout);
	framebuf_render(&out0154_png);
	usleep(timeout);
	framebuf_render(&out0155_png);
	usleep(timeout);
	framebuf_render(&out0156_png);
	usleep(timeout);
	framebuf_render(&out0157_png);
	usleep(timeout);
	framebuf_render(&out0158_png);
	usleep(timeout);
	framebuf_render(&out0159_png);
	usleep(timeout);
	framebuf_render(&out0160_png);
	usleep(timeout);
	framebuf_render(&out0161_png);
	usleep(timeout);
	framebuf_render(&out0162_png);
	usleep(timeout);
	framebuf_render(&out0163_png);
	usleep(timeout);
	framebuf_render(&out0164_png);
	usleep(timeout);
	framebuf_render(&out0165_png);
	usleep(timeout);
	framebuf_render(&out0166_png);
	usleep(timeout);
	framebuf_render(&out0167_png);
	usleep(timeout);
	framebuf_render(&out0168_png);
	usleep(timeout);
	framebuf_render(&out0169_png);
	usleep(timeout);
	framebuf_render(&out0170_png);
	usleep(timeout);
	framebuf_render(&out0171_png);
	usleep(timeout);
	framebuf_render(&out0172_png);
	usleep(timeout);
	}
}
